[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Generic Tasks", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Mutations", "openItem": "False", "children": [
	         {"tag": "protocol", "value": "ProtRosettaFlexDDG",   "text": "default"}
	    ]},
	]},
	{"tag": "section", "text": "Preparation", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Target Preparation", "openItem": "False", "children": [
	         {"tag": "protocol", "value": "RosettaProteinPreparation",   "text": "default"}
	    ]}
	]}
    ]
