[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Preparation", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Target Preparation", "openItem": "False", "children": [
	         {"tag": "protocol", "value": "RosettaProteinPreparation",   "text": "default"}
	    ]}
	]},
    {"tag": "section", "text": "Docking", "icon": "bookmark.png", "children": [
         {"tag": "protocol", "value": "RosettaProtDARC",   "text": "default"}
	]}
    ]
